"""back to before 

Revision ID: 03b12f75271e
Revises: 7ca8d93c20c9
Create Date: 2024-07-07 04:29:42.140905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03b12f75271e'
down_revision = '7ca8d93c20c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('matches_ibfk_3', type_='foreignkey')
        batch_op.drop_column('claim_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('matches_ibfk_3', 'claims', ['claim_id'], ['id'])

    # ### end Alembic commands ###
