"""quality changes quality_checker_user_id

Revision ID: 27faedf9d497
Revises: e764a6edaed9
Create Date: 2024-07-09 16:40:06.757617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27faedf9d497'
down_revision = 'e764a6edaed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_checker_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['quality_checker_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quality_checker_user_id')

    # ### end Alembic commands ###
