"""current head back to the begining before  match table

Revision ID: 28e0a0d443c1
Revises: 39a216d51f11
Create Date: 2024-07-27 13:07:07.659212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28e0a0d443c1'
down_revision = '39a216d51f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('matches_ibfk_4', type_='foreignkey')
        batch_op.drop_column('lost_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lost_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('matches_ibfk_4', 'items', ['lost_item_id'], ['id'])

    # ### end Alembic commands ###
