"""added new status to items closed

Revision ID: 44799b5bc6ee
Revises: 28e0a0d443c1
Create Date: 2024-07-29 02:20:33.033092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44799b5bc6ee'
down_revision = '28e0a0d443c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('Lost', 'Found'), nullable=False))

    # ### end Alembic commands ###
