"""delete match table - quality_checker_user_id

Revision ID: 5211a6ff5a5f
Revises: 27faedf9d497
Create Date: 2024-07-09 16:43:40.310089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5211a6ff5a5f'
down_revision = '27faedf9d497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('matches_ibfk_4', type_='foreignkey')
        batch_op.drop_column('quality_checker_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_checker_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('matches_ibfk_4', 'users', ['quality_checker_user_id'], ['id'])

    # ### end Alembic commands ###
