"""the changes on item table2

Revision ID: 6470d55d95c1
Revises: d7d0e02ea17f
Create Date: 2024-07-24 11:47:11.682934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6470d55d95c1'
down_revision = 'd7d0e02ea17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_lost_found', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('location_lost_found', sa.String(length=255), nullable=False))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('location_lost_found')
        batch_op.drop_column('date_lost_found')

    # ### end Alembic commands ###
