"""the changes on vlaim addded image url

Revision ID: 7f0561c0c935
Revises: 6470d55d95c1
Create Date: 2024-07-24 12:32:19.517985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0561c0c935'
down_revision = '6470d55d95c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
