"""contact db change

Revision ID: 833af22e282f
Revises: 7f0561c0c935
Create Date: 2024-07-26 13:30:32.661495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833af22e282f'
down_revision = '7f0561c0c935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
