"""the changes on item table

Revision ID: d7d0e02ea17f
Revises: 5211a6ff5a5f
Create Date: 2024-07-24 11:38:59.453908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7d0e02ea17f'
down_revision = '5211a6ff5a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('item_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('item_category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('item_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('item_brand', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_lost_found', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('location_lost_found', sa.String(length=255), nullable=False))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('location_lost_found')
        batch_op.drop_column('date_lost_found')
        batch_op.drop_column('item_brand')
        batch_op.drop_column('item_color')
        batch_op.drop_column('item_category')
        batch_op.drop_column('item_name')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
