"""quality_checker_user_id in quality check table

Revision ID: e764a6edaed9
Revises: ea1aa023cf1a
Create Date: 2024-07-07 05:11:52.052258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e764a6edaed9'
down_revision = 'ea1aa023cf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quality_checker_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['quality_checker_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quality_checker_user_id')
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
