"""added new status to items closed2

Revision ID: fc27e15e358f
Revises: 44799b5bc6ee
Create Date: 2024-07-29 02:21:05.153424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc27e15e358f'
down_revision = '44799b5bc6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Lost', 'Found', 'Report', 'Closed', name='status_types'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
